repos:
  - repo: local
    hooks:
      - id: clean-config-files
        name: Clean Config Files
        entry: python clean_paths_files.py
        language: python
        types: [text]
        args: [ "dummy/file_param_name.extension"]
        stages: [commit]