-   id: clean-config-files
    name: Clean Config Files
    entry: python3 clean_paths_files.py
    language: system
    args: ["/PMBB", "/home/user", "/var/data", "/project", "--directories=Plink_2_0_GWAS"]
    stages: [commit]

-   id: check-for-cluster-paths
    name: Check for cluster paths in all committed files
    description: prevents cluster paths from being leaked.
    entry: python3 check-files-for-strings
    language: system
    args: [--search-string, "/project/", --quiet-skip-binary]
    stages: [commit, push, manual]

-   id: check-for-home-paths
    name: Check for home directory paths in all committed files
    description: prevents home paths/names from being leaked.
    entry: python3 check-files-for-strings
    language: system
    args: [--search-string, "/home/", --quiet-skip-binary]
    stages: [commit, push, manual]

-   id: check-for-data-strings
    name: Check for PMBB strings in all committed files
    description: prevents missing usage of PMBB data (and paths) from being leaked.
    entry: python3 check-files-for-strings
    language: system
    args: [--search-string, "PMBB", --case-insensitive, --quiet-skip-binary]
    stages: [commit, push, manual]

-   id: check-added-binary-files
    name: Check for binary files in all committed files
    description: prevents binary files from being committed.
    entry: python3 check-added-binary-files
    language: system
    args: [--enforce-all]
    stages: [commit, push, manual]

-   id: check-for-container-default
    name: Check that containers are defined with a default value
    description: prevents containers pointing to personal repos from being committed.
    entry: python3 check-for-container-default
    language: system
    args: [--enforce-all]
    stages: [commit, push, manual]
