repos:
  - repo: local
    hooks:
      - id: clean-config-files
        name: Clean Config Files
        entry: python clean_paths_files.py
        language: python
        files: test_file.py
        args: 
          - "/PMBB"
        stages: [commit]
