repos:
  - repo: local
    hooks:
      - id: clean-config-files
        name: Clean Config Files
        entry: python clean_paths_files.py
        language: system
        files: test_file.py
        stages: [commit]
